"""AI prompt templates and colocated response models."""

from .assess.models import (
    CEFRLevelResponse,
    Collocation,
    CollocationResponse,
    DomainIdentificationResponse,
    FrequencyBandResponse,
    GrammarPatternResponse,
    RegionalVariantResponse,
    RegisterClassificationResponse,
    UsageNote,
    UsageNoteResponse,
)
from .generate.models import (
    ExampleGenerationResponse,
    ExampleSynthesisResponse,
    FactGenerationResponse,
    WordForm,
    WordFormResponse,
)
from .misc.models import (
    AnkiFillBlankResponse,
    AnkiMultipleChoiceResponse,
    CandidateRanking,
    ClusterMapping,
    ClusterMappingResponse,
    MeaningClusterResponse,
    QueryValidationResponse,
    RankingResponse,
    Suggestion,
    SuggestionsResponse,
    WordSuggestion,
    WordSuggestionResponse,
)
from .shared.models import (
    AIGeneratedProviderData,
    ComprehensiveSynthesisResponse,
    EnhancedDefinitionResponse,
    TextGenerationRequest,
    TextGenerationResponse,
)
from .synthesize.models import (
    AntonymCandidate,
    AntonymResponse,
    DeduplicatedDefinition,
    DeduplicationResponse,
    DefinitionResponse,
    DefinitionSynthesisResponse,
    DictionaryEntryResponse,
    EtymologyResponse,
    PronunciationResponse,
    SynonymCandidate,
    SynonymGenerationResponse,
    SynthesisResponse,
)
from .wotd.models import (
    LiteratureAnalysis,
    LiteratureAnalysisResponse,
    LiteratureAugmentation,
    LiteratureAugmentationRequest,
    LiteratureAugmentationResponse,
    LiteratureCharacteristics,
    LiteratureMetadata,
    LiteratureQualityMetrics,
    SemanticID,
    SyntheticCorpusResponse,
    SyntheticWordEntry,
    WordOfTheDayResponse,
)

__all__ = [
    # assess
    "CEFRLevelResponse",
    "Collocation",
    "CollocationResponse",
    "DomainIdentificationResponse",
    "FrequencyBandResponse",
    "GrammarPatternResponse",
    "RegionalVariantResponse",
    "RegisterClassificationResponse",
    "UsageNote",
    "UsageNoteResponse",
    # generate
    "ExampleGenerationResponse",
    "ExampleSynthesisResponse",
    "FactGenerationResponse",
    "WordForm",
    "WordFormResponse",
    # misc
    "AnkiFillBlankResponse",
    "AnkiMultipleChoiceResponse",
    "CandidateRanking",
    "ClusterMapping",
    "ClusterMappingResponse",
    "MeaningClusterResponse",
    "QueryValidationResponse",
    "RankingResponse",
    "Suggestion",
    "SuggestionsResponse",
    "WordSuggestion",
    "WordSuggestionResponse",
    # shared
    "AIGeneratedProviderData",
    "ComprehensiveSynthesisResponse",
    "EnhancedDefinitionResponse",
    "TextGenerationRequest",
    "TextGenerationResponse",
    # synthesize
    "AntonymCandidate",
    "AntonymResponse",
    "DeduplicatedDefinition",
    "DeduplicationResponse",
    "DefinitionResponse",
    "DefinitionSynthesisResponse",
    "DictionaryEntryResponse",
    "EtymologyResponse",
    "PronunciationResponse",
    "SynonymCandidate",
    "SynonymGenerationResponse",
    "SynthesisResponse",
    # wotd
    "LiteratureAnalysis",
    "LiteratureAnalysisResponse",
    "LiteratureAugmentation",
    "LiteratureAugmentationRequest",
    "LiteratureAugmentationResponse",
    "LiteratureCharacteristics",
    "LiteratureMetadata",
    "LiteratureQualityMetrics",
    "SemanticID",
    "SyntheticCorpusResponse",
    "SyntheticWordEntry",
    "WordOfTheDayResponse",
]
