"""Convenience exports for frequently used model types.

Historically the project imported everything from ``floridify.models``.
To keep mypy happy without touching dozens of call sites, we re-export the
common classes here while still encouraging direct sub-module imports.
"""

from .base import AudioMedia, BaseMetadata, ImageMedia, Language, ModelInfo
from .dictionary import (
    Definition,
    DictionaryEntry,
    DictionaryProvider,
    Etymology,
    Example,
    Fact,
    LiteratureSourceExample,
    Pronunciation,
    Word,
)
from .literature import AuthorInfo, Genre, Period
from .parameters import (
    CacheClearParams,
    CacheStatsParams,
    ConfigGetParams,
    ConfigSetParams,
    CorpusCreateParams,
    CorpusListParams,
    DatabaseCleanupParams,
    DatabaseStatsParams,
    LookupParams,
    PaginationParams,
    ProviderStatusParams,
    SearchParams,
    SortParams,
    WordlistCreateParams,
)
from .relationships import Collocation, GrammarPattern, MeaningCluster, UsageNote, WordForm
from .responses import (
    AnkiExportResponse,
    BatchOperationResponse,
    CacheStatsResponse,
    ConfigResponse,
    CorpusListResponse,
    CorpusResponse,
    DatabaseStatsResponse,
    ErrorResponse,
    HealthResponse,
    IndexRebuildResponse,
    ListResponse,
    LookupResponse,
    ProviderListResponse,
    ProviderStatusResponse,
    SearchResponse,
    SuccessResponse,
    WordlistResponse,
)

__all__ = [
    # Base models
    "AudioMedia",
    "AuthorInfo",
    "BaseMetadata",
    "Collocation",
    "Definition",
    "DictionaryEntry",
    "DictionaryProvider",
    "Etymology",
    "Example",
    "Fact",
    "Genre",
    "GrammarPattern",
    "ImageMedia",
    "Language",
    "LiteratureSourceExample",
    "MeaningCluster",
    "ModelInfo",
    "Period",
    "Pronunciation",
    "UsageNote",
    "Word",
    "WordForm",
    # Shared parameter models
    "CacheClearParams",
    "CacheStatsParams",
    "ConfigGetParams",
    "ConfigSetParams",
    "CorpusCreateParams",
    "CorpusListParams",
    "DatabaseCleanupParams",
    "DatabaseStatsParams",
    "LookupParams",
    "PaginationParams",
    "ProviderStatusParams",
    "SearchParams",
    "SortParams",
    "WordlistCreateParams",
    # Shared response models
    "AnkiExportResponse",
    "BatchOperationResponse",
    "CacheStatsResponse",
    "ConfigResponse",
    "CorpusListResponse",
    "CorpusResponse",
    "DatabaseStatsResponse",
    "ErrorResponse",
    "HealthResponse",
    "IndexRebuildResponse",
    "ListResponse",
    "LookupResponse",
    "ProviderListResponse",
    "ProviderStatusResponse",
    "SearchResponse",
    "SuccessResponse",
    "WordlistResponse",
]
