"""William Shakespeare - English Playwright and Poet (1564-1616).

Comprehensive mapping of Shakespeare's works available on Project Gutenberg.
"""

from ....models.dictionary import Language
from ....corpus.literature.models import AuthorInfo, Genre, LiteraryWork, Period

AUTHOR = AuthorInfo(
    name="William Shakespeare",
    birth_year=1564,
    death_year=1616,
    nationality="English",
    period=Period.RENAISSANCE,
    primary_genre=Genre.DRAMA,
    language=Language.ENGLISH,
    gutenberg_author_id="65",
)

WORKS = [
    # Complete Collections
    LiteraryWork(
        title="The Complete Works of William Shakespeare",
        author=AUTHOR,
        gutenberg_id="100",
        year=1623,
        genre=Genre.DRAMA,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="Shakespeare's First Folio",
        author=AUTHOR,
        gutenberg_id="2270",
        year=1623,
        genre=Genre.DRAMA,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="Shakespeare's Sonnets",
        author=AUTHOR,
        gutenberg_id="1041",
        year=1609,
        genre=Genre.POETRY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    # Major Tragedies
    LiteraryWork(
        title="Hamlet, Prince of Denmark",
        author=AUTHOR,
        gutenberg_id="1524",
        year=1603,
        genre=Genre.TRAGEDY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="Macbeth",
        author=AUTHOR,
        gutenberg_id="1533",
        year=1606,
        genre=Genre.TRAGEDY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="Othello, the Moor of Venice",
        author=AUTHOR,
        gutenberg_id="1531",
        year=1603,
        genre=Genre.TRAGEDY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="King Lear",
        author=AUTHOR,
        gutenberg_id="1532",
        year=1605,
        genre=Genre.TRAGEDY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="Romeo and Juliet",
        author=AUTHOR,
        gutenberg_id="1513",
        year=1595,
        genre=Genre.TRAGEDY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="Julius Caesar",
        author=AUTHOR,
        gutenberg_id="1522",
        year=1599,
        genre=Genre.TRAGEDY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="Antony and Cleopatra",
        author=AUTHOR,
        gutenberg_id="1534",
        year=1606,
        genre=Genre.TRAGEDY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="Coriolanus",
        author=AUTHOR,
        gutenberg_id="1535",
        year=1608,
        genre=Genre.TRAGEDY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="Timon of Athens",
        author=AUTHOR,
        gutenberg_id="1132",
        year=1608,
        genre=Genre.TRAGEDY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="Titus Andronicus",
        author=AUTHOR,
        gutenberg_id="1507",
        year=1594,
        genre=Genre.TRAGEDY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    # Major Comedies
    LiteraryWork(
        title="A Midsummer Night's Dream",
        author=AUTHOR,
        gutenberg_id="1514",
        year=1595,
        genre=Genre.COMEDY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="Much Ado About Nothing",
        author=AUTHOR,
        gutenberg_id="1519",
        year=1598,
        genre=Genre.COMEDY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="The Merchant of Venice",
        author=AUTHOR,
        gutenberg_id="1515",
        year=1596,
        genre=Genre.COMEDY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="As You Like It",
        author=AUTHOR,
        gutenberg_id="1523",
        year=1599,
        genre=Genre.COMEDY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="Twelfth Night",
        author=AUTHOR,
        gutenberg_id="1526",
        year=1601,
        genre=Genre.COMEDY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="The Taming of the Shrew",
        author=AUTHOR,
        gutenberg_id="1508",
        year=1593,
        genre=Genre.COMEDY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="The Tempest",
        author=AUTHOR,
        gutenberg_id="23042",
        year=1611,
        genre=Genre.COMEDY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="The Winter's Tale",
        author=AUTHOR,
        gutenberg_id="1539",
        year=1611,
        genre=Genre.COMEDY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="Measure for Measure",
        author=AUTHOR,
        gutenberg_id="23045",
        year=1604,
        genre=Genre.COMEDY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    # History Plays
    LiteraryWork(
        title="King Richard III",
        author=AUTHOR,
        gutenberg_id="1503",
        year=1592,
        genre=Genre.HISTORY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="King Henry IV, Part 1",
        author=AUTHOR,
        gutenberg_id="1516",
        year=1597,
        genre=Genre.HISTORY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="King Henry IV, Part 2",
        author=AUTHOR,
        gutenberg_id="1518",
        year=1598,
        genre=Genre.HISTORY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="King Henry V",
        author=AUTHOR,
        gutenberg_id="1521",
        year=1599,
        genre=Genre.HISTORY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="King Henry VI, Part 1",
        author=AUTHOR,
        gutenberg_id="1500",
        year=1591,
        genre=Genre.HISTORY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="King Henry VI, Part 2",
        author=AUTHOR,
        gutenberg_id="1501",
        year=1591,
        genre=Genre.HISTORY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="King Henry VI, Part 3",
        author=AUTHOR,
        gutenberg_id="1502",
        year=1592,
        genre=Genre.HISTORY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
    LiteraryWork(
        title="King Richard II",
        author=AUTHOR,
        gutenberg_id="1512",
        year=1595,
        genre=Genre.HISTORY,
        period=Period.RENAISSANCE,
        language=Language.ENGLISH,
    ),
]


def get_works() -> list[LiteraryWork]:
    """Get all works by Shakespeare."""
    return WORKS


def get_author() -> AuthorInfo:
    """Get author information."""
    return AUTHOR
